### ISSUE TITLE
mac build error

### ISSUE THREAD

**Issue by calvintam236** [z-classic/zclassic#111]
### Describe the issue
```console
$ ./zcutil/build-mac.sh
.... skipped ...
In file included from /usr/include/sys/cdefs.h:587:0,
                 from /usr/include/stdio.h:64,
                 from crypto/bio/bss_log.c:19:
/usr/include/sys/syslog.h:227:124: error: expected ',' or ';' before '__asm'
 void syslog(int, const char *, ...) __printflike(2, 3) __not_tail_called __DARWIN_ALIAS_STARTING(__MAC_10_13, __IPHONE_NA, __DARWIN_EXTSN(syslog));
                                                                                                                            ^
make[2]: *** [crypto/bio/bss_log.o] Error 1
make[1]: *** [build_libs] Error 2
make: *** [/Users/???/Documents/tmp/zclassic/depends/work/build/x86_64-apple-darwin17.0.0/openssl/1.1.0d-d30985ea543/./.stamp_built] Error 2
```

macOS 10.13
```console
$ brew install cmake autoconf libtool automake coreutils pkgconfig gmp wget
Warning: cmake 3.10.0 is already installed
Warning: autoconf 2.69 is already installed
Warning: libtool 2.4.6_1 is already installed
Warning: automake 1.15.1 is already installed
Warning: coreutils 8.28_1 is already installed
Warning: pkg-config 0.29.2 is already installed
Warning: gmp 6.1.2_1 is already installed
Warning: wget 1.19.2 is already installed
$ brew install gcc5 --without-multilib
Warning: gcc@5 5.5.0 is already installed
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by fr3nch13** [comment]
I'm running into this issue as well. Apparently its a bug with syslog headers in Xcode. I still haven't found a solution.

**Comment by heyrhett** [comment]
This is something to do with High Sierra

**Comment by aribo** [comment]
I have the same on High Sierra.

**Comment by heyrhett** [comment]
Fixed with https://github.com/z-classic/zclassic/commit/9acef66abdfc6133124299b91a65e9e10f2806e9

**Comment by aribo** [comment]
Still have some errors:

./libtool: fork: Resource temporarily unavailable
make[1]: *** [db_err.o] Error 128
libtool: compile:  gcc-5 -mmacosx-version-min=10.7 -c -I. -I../dist/./../src -I/Users/Alejandro/zclassic/depends/x86_64-apple-darwin17.3.0/include -pipe -O2 ../dist/./../src/common/db_compint.c -o db_compint.o
libtool: compile:  gcc-5 -mmacosx-version-min=10.7 -c -I. -I../dist/./../src -I/Users/Alejandro/zclassic/depends/x86_64-apple-darwin17.3.0/include -pipe -O2 ../dist/./../src/db/db_conv.c -o db_conv.o
libtool: compile:  gcc-5 -mmacosx-version-min=10.7 -c -I. -I../dist/./../src -I/Users/Alejandro/zclassic/depends/x86_64-apple-darwin17.3.0/include -pipe -O2 ../dist/./../src/db/db_copy.c -o db_copy.o
make[1]: *** [db_cam.o] Error 1
make: *** [/Users/Alejandro/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/bdb/6.2.23-9ffc989134d/build_unix/.stamp_built] Error 2

**Comment by josephnicholas** [comment]
**[Josephs-MacBook-Pro:zclassic josephnicholasr.alcantara$ ./zcutil/build-mac.sh -j$(sysctl -n hw.ncpu)**

_This is my firs time to build zclassic, and I have some issues below. I am running on macOS 10.13.2, and I have downloaded the dependencies. What seems to be the problem?_

> mkdir -p /Volumes/Dev/Z-Classic/zclassic/depends/sources/download-stamps /Volumes/Dev/Z-Classic/zclassic/depends/sources
> rm -f /Volumes/Dev/Z-Classic/zclassic/depends/sources/download-stamps/.stamp_fetched-native_ccache-ccache-3.3.1.tar.bz2.hash
> touch /Volumes/Dev/Z-Classic/zclassic/depends/sources/download-stamps/.stamp_fetched-native_ccache-ccache-3.3.1.tar.bz2.hash
> cd /Volumes/Dev/Z-Classic/zclassic/depends/sources/download-stamps; (test -f /Volumes/Dev/Z-Classic/zclassic/depends/sources/ccache-3.3.1.tar.bz2 || ( mkdir -p /Volumes/Dev/Z-Classic/zclassic/depends/work/download/native_ccache-3.3.1 && echo Fetching native_ccache... && ( curl --connect-timeout 10 --retry 3 -L -f -o "/Volumes/Dev/Z-Classic/zclassic/depends/work/download/native_ccache-3.3.1/ccache-3.3.1.tar.bz2.temp" "https://z.cash/depends-sources/ccache-3.3.1.tar.bz2" || curl --connect-timeout 10 --retry 3 -L -f -o "/Volumes/Dev/Z-Classic/zclassic/depends/work/download/native_ccache-3.3.1/ccache-3.3.1.tar.bz2.temp" "https://www.samba.org/ftp/ccache/ccache-3.3.1.tar.bz2" ) && echo "cb6e4bafbb19ba0a2ec43386b123a5f92a20e1e3384c071d5d13e0cb3c84bf73  /Volumes/Dev/Z-Classic/zclassic/depends/work/download/native_ccache-3.3.1/ccache-3.3.1.tar.bz2.temp" > /Volumes/Dev/Z-Classic/zclassic/depends/work/download/native_ccache-3.3.1/.ccache-3.3.1.tar.bz2.hash && shasum -a 256 -c /Volumes/Dev/Z-Classic/zclassic/depends/work/download/native_ccache-3.3.1/.ccache-3.3.1.tar.bz2.hash && mv /Volumes/Dev/Z-Classic/zclassic/depends/work/download/native_ccache-3.3.1/ccache-3.3.1.tar.bz2.temp /Volumes/Dev/Z-Classic/zclassic/depends/sources/ccache-3.3.1.tar.bz2 && rm -rf /Volumes/Dev/Z-Classic/zclassic/depends/work/download/native_ccache-3.3.1 ))
> Fetching native_ccache...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  337k  100  337k    0     0  42352      0  0:00:08  0:00:08 --:--:-- 82233
> /Volumes/Dev/Z-Classic/zclassic/depends/work/download/native_ccache-3.3.1/ccache-3.3.1.tar.bz2.temp: OK
> cd /Volumes/Dev/Z-Classic/zclassic/depends/sources; shasum -a 256 ccache-3.3.1.tar.bz2 >> /Volumes/Dev/Z-Classic/zclassic/depends/sources/download-stamps/.stamp_fetched-native_ccache-ccache-3.3.1.tar.bz2.hash;
> touch /Volumes/Dev/Z-Classic/zclassic/depends/sources/download-stamps/.stamp_fetched-native_ccache-ccache-3.3.1.tar.bz2.hash
> echo Extracting native_ccache...
> Extracting native_ccache...
> mkdir -p /Volumes/Dev/Z-Classic/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/native_ccache/3.3.1-46021dfbdf9
> cd /Volumes/Dev/Z-Classic/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/native_ccache/3.3.1-46021dfbdf9; mkdir -p /Volumes/Dev/Z-Classic/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/native_ccache/3.3.1-46021dfbdf9 && echo "cb6e4bafbb19ba0a2ec43386b123a5f92a20e1e3384c071d5d13e0cb3c84bf73  /Volumes/Dev/Z-Classic/zclassic/depends/sources/ccache-3.3.1.tar.bz2" > /Volumes/Dev/Z-Classic/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/native_ccache/3.3.1-46021dfbdf9/.ccache-3.3.1.tar.bz2.hash &&  shasum -a 256 -c /Volumes/Dev/Z-Classic/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/native_ccache/3.3.1-46021dfbdf9/.ccache-3.3.1.tar.bz2.hash && tar --strip-components=1 -xf /Volumes/Dev/Z-Classic/zclassic/depends/sources/ccache-3.3.1.tar.bz2
> /Volumes/Dev/Z-Classic/zclassic/depends/sources/ccache-3.3.1.tar.bz2: OK
> touch /Volumes/Dev/Z-Classic/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/native_ccache/3.3.1-46021dfbdf9/.stamp_extracted
> echo Preprocessing native_ccache...
> Preprocessing native_ccache...
> mkdir -p /Volumes/Dev/Z-Classic/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/native_ccache/3.3.1-46021dfbdf9 /Volumes/Dev/Z-Classic/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/native_ccache/3.3.1-46021dfbdf9/.patches-46021dfbdf9
> cd /Volumes/Dev/Z-Classic/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/native_ccache/3.3.1-46021dfbdf9; 
> touch /Volumes/Dev/Z-Classic/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/native_ccache/3.3.1-46021dfbdf9/.stamp_preprocessed
> echo Configuring native_ccache...
> Configuring native_ccache...
> rm -rf /Volumes/Dev/Z-Classic/zclassic/depends/x86_64-apple-darwin17.3.0; mkdir -p /Volumes/Dev/Z-Classic/zclassic/depends/x86_64-apple-darwin17.3.0/lib; cd /Volumes/Dev/Z-Classic/zclassic/depends/x86_64-apple-darwin17.3.0; 
> mkdir -p /Volumes/Dev/Z-Classic/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/native_ccache/3.3.1-46021dfbdf9/.
> cd /Volumes/Dev/Z-Classic/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/native_ccache/3.3.1-46021dfbdf9/.;     PKG_CONFIG_LIBDIR=/Volumes/Dev/Z-Classic/zclassic/depends/x86_64-apple-darwin17.3.0/native/lib/pkgconfig PKG_CONFIG_PATH=/Volumes/Dev/Z-Classic/zclassic/depends/x86_64-apple-darwin17.3.0/native/share/pkgconfig PATH=/Volumes/Dev/Z-Classic/zclassic/depends/x86_64-apple-darwin17.3.0/native/bin:/Users/josephnicholasr.alcantara/miniconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands   ./configure --host=x86_64-apple-darwin17.3.0 --disable-dependency-tracking --prefix=/Volumes/Dev/Z-Classic/zclassic/depends/x86_64-apple-darwin17.3.0/native         CC="gcc-5" CXX="g++-5" NM="nm" RANLIB="ranlib" AR="ar" CPPFLAGS="-I/Volumes/Dev/Z-Classic/zclassic/depends/x86_64-apple-darwin17.3.0/native/include    " LDFLAGS="-L/Volumes/Dev/Z-Classic/zclassic/depends/x86_64-apple-darwin17.3.0/native/lib    "
> /bin/sh: Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands: No such file or directory
> make: *** [/Volumes/Dev/Z-Classic/zclassic/depends/work/build/x86_64-apple-darwin17.3.0/native_ccache/3.3.1-46021dfbdf9/./.stamp_configured] Error 127

**Comment by fr3nch13** [comment]
It looks to me like you missing something, or your $PATH is missing something while processing ccache

https://stackoverflow.com/questions/36365752/make-error-127



----------------------------------
BRIAN FRENCH
fr3nch13@gmail.com
703-507-5383

**Comment by josephnicholas** [comment]
@fr3nch13 , what would be the correct $PATH for this. Mine says

> /Users/josephnicholasr.alcantara/miniconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware: No such file or directory
